### ISSUE TITLE
Another pass at JuDoc-ing the official Julia blog

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#221]
Hi Thibaut! Wow, you've been working hard, I see... ! 

I thought I'd make another pass at pushing the official Julia blog through JuDoc, and decided to attempt a full replicant, which you can find on Netlify at [https://julialangblogmirror.netlify.com](https://julialangblogmirror.netlify.com) (Github repo [here](https://github.com/cormullion/julialangblog)). I think it's 95% there.

Probably the main thing to add before using it as a good example of JuDoc's power would be code-highlighting - I haven't looked at that at all. And CSS tweaking always offers fertile ground for the procrastinator...!  :)

A few minor syntax oddities I noticed (and it was easy enough to work around them):

`` **`master`** `` - people hoping to `strong`-ify a `code`d term currently not working? Similarly, I noticed someone typing ``` ** x\* ** ``` hoping for bold maths  **x\*** - instead I hit it with tildes until it yielded: ```~~~<strong>x*</strong>~~~```. I think it's fair that, to some extent, you have to write to a particular format.

`` ``` ... ``` `` used in the middle of a paragraph inserts line breaks, but people wouldn't expect that? I just changed them to the new ``` `` ... `` ```.

In Tim Besard's post ([original](https://julialang.org/blog/2017/03/cudanative), [original source](https://github.com/JuliaLang/www.julialang.org/blob/master/blog/_posts/2017-03-14-cudanative.md), [replicant](https://julialangblogmirror.netlify.com/pub/2017-03-14-cudanative.html)), he defines a "variable" `cudanative_tree` then uses it to build links into GitHub:

```[^1]: See the [README]({{page.cudanative_tree}}/README.md#object-arguments) for a note on how expensive this currently is.``` (Jekyll)

I had a go at doing something similar using the JuDoc command syntax but I couldn't get it working. Not sure whether I understand it all sufficiently, or whether there are interactions between links/footnotes/commands that need ironing out.

**Comment by tlienart** [comment]
Fantastic thanks, here's a list of actions following your post + things I see from the netlify repro

* footnotes -- yes, it's something I haven't looked at yet (#100)
* strong-ifying code seemed a bit odd to me so I think I intentionally prevented that case some time back but the example you give makes a lot of sense and GitHub likes it too: **`master`**, issue opened (#222)
* `** x\* **` this should work, so it's a bug (#223)
* triple quotes insert line breaks: yes this was intentional but I see that as per common mark, it should not be the case for something like ````` ```hello``` ````` which should show like ```hello``` . (Who would have thought Markdown had so many interesting corner cases 🤔 )

### Other stuff

* I'll play a bit with your repo to try to get the syntax highlighting working etc and see if I can find more quirks
* I found this test suite for Common Mark: https://github.com/michelf/mdtest/ will try to see whether it can help track down more issues

Again thanks a lot for your help!

**Comment by cormullion** [comment]
Cool! Shall I add you as a collaborator on that repo?

**Comment by tlienart** [comment]
yes please!

**Comment by tlienart** [comment]
I'm closing this as the repo in action is now looking pretty good if I may say so myself and the few remaining quirks (footnotes, and some mode of bold/code) have their own issue, thanks again for all the help!!
