### ISSUE TITLE
Odd quirks in build/highlighting process

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#259]
As I was trying to get the code highlighting working on the JuliaLangBlogMirror, I encountered some `err = StringIndexError("<!doctype html>...` errors, including one in `2016-08-22-GSoC2016-Graft.md` and two others, which you refer to in the [readme](https://github.com/cormullion/julialangblog/blob/master/README.md).

1. The first problem I fixed by making this change:

<img width="300" alt="Screenshot 2019-10-09 at 09 19 48" src="https://user-images.githubusercontent.com/52289/66463911-f391c280-ea75-11e9-8706-633d76430c3c.png">

ie just inserting an empty line between the `│` (Unicode U+2502) and the concluding ` ``` `. I have no idea what the problem was or why this worked... :)

2. To get [this file](https://github.com/cormullion/julialangblog/blob/2c0ecff4b95f7419bd7bad0fe1a0b9d262a0c657/src/pages/2018-08-08-one-point-zero-zh_cn.md) through I removed the indentation of a paragraph. Again, ¯\\\_(ツ)_/¯ !

3. To get [this file](https://github.com/cormullion/julialangblog/blob/2c0ecff4b95f7419bd7bad0fe1a0b9d262a0c657/src/pages/2019-04-04-fluxdiffeq-zh_tw.md) through I removed one of those circular periods (Unicode U+3002) from inside the maths block:

```
$$y_{i+1} = y_{i} + \Delta x\cdot ML(x_{i}) $$ <!-- removed 。-->
```

That kind of makes sense, anyway... :)

(Also, I had a few questions about the set-up for node highlighting. I ended up with a folder called `node-modules` in the blog's root directory (I didn't add it to the repo). Should it be there?)

**Comment by tlienart** [comment]
Oh  that's very helpful.

- when an error is fixed by adding spaces, it typically points towards a use of string indexing instead of use of `prevind`, `nextind`, I'll investigate.

Could you point me to the diff for (2) and (3)? would be interesting to know exactly what happened. Though yes unicode and KaTeX may not like each other.

###  Node highlighting

You should not need a `node-modules` in the blog's root directory. There's basically "two" ways code gets highlighted:

- before prerendering  --> this uses the file `/libs/highlight/highlight.pack.js`
- with  prerendering --> this uses your local installation of the package `highlight.js` and calls a line like `node -e "const hljs = require('highlight.js');"`  

The first thing should "just work™️"  in all cases, the second will work assuming that you have a working `highlight` installed locally. You can inspect the latter with `JuDoc.JD_CAN_HIGHLIGHT` if that's true then in the prerendering step it will just call that which will do the higlighting.

Oh and the final element is the CSS file but that's the same in all cases `libs/highlight/github.min.css`

Does that make sense? so assuming `JuDoc.JD_CAN_HIGHLIGHT` is true, you should not need anything else. To make it true if it isn't, you should try following the installation instruction [here](https://tlienart.github.io/JuDoc.jl/dev/#External-dependencies-1)

**Comment by tlienart** [comment]
Hmm ok so I  think this is the offending code:

https://github.com/tlienart/JuDoc.jl/blob/0e1fe94b5fc2bd06fbb99c9fe7494007ffc186ac/src/converter/js_prerender.jl#L27

https://github.com/tlienart/JuDoc.jl/blob/master/src/converter/js_prerender.jl#L64

So if you have unicode stuff at the beginning of end of the expresssion things can fail because I'm using direct string indexing and I should have been using nextind/prevind.

**Comment by tlienart** [comment]
Ok I fixed both of these, tested on the original markdown and I believe it fixes the problem.

Let me know if the highlighting thing makes sense

**Comment by cormullion** [comment]
Awesome! You're very quick... :)

It's not urgent now (since I must do other stuff), but I can't get highlighting working without installing it in the blog directory.

Julia and I can see `node`:

```
julia-1.2> success(`node -v`)
true
```

but Julia can't find highlighting:

```
(v1.2) pkg> build JuDoc
  Building MbedTLS → `~/.julia/packages/MbedTLS/a1JFn/deps/build.log`
julia-1.2> using JuDoc; JuDoc.JD_CAN_HIGHLIGHT
false
```

I think I've installed it OK - well, I did this:

```
$ $ npm install -g highlight.js
+ highlight.js@9.15.10
updated 1 package in 0.407s
```

and it looks like it installed OK:

```
$ ls /usr/local/lib/node_modules/
highlight.js	npm
```

and I exported the PATH to point there:

```
PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/Applications/Julia-1.2.app/Contents/Resources/julia/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/opt/X11/bin:/usr/local/git/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/lib/node_modules
```

and Julia can see that path:

```
julia-1.2> ENV["PATH"]
"/Library/Frameworks/Python.framework/Versions/3.6/bin:/Applications/Julia-
...
/usr/local/lib/node_modules"
```

so I'm missing something obvious about why JuDoc can't see `highlight` ...  ¯\\_(ツ)_/¯  

There's a NodeJS package in the registry - I wonder whether that might be more reliable?

**Comment by tlienart** [comment]
I'll consider using NodeJS, thanks for that!
