### ISSUE TITLE
IOError 'chmod 644' issue for favicon.png

### ISSUE THREAD

**Issue by virenbhanot** [tlienart/JuDoc.jl#305]
Using JuDoc.jl v0.3.8 on Windows 10 with Julia v1.2.0. When I type in the `newsite("Test")` command, I get the following error: 

> ERROR: IOError: could not spawn `chmod 644 'Test\assets\infra\favicon.png'`: no such file or directory (ENOENT)

> Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:401
 [2] setup_stdios(::getfield(Base, Symbol("##526#527")){Cmd}, ::Array{Any,1}) at .\process.jl:414
 [3] _spawn at .\process.jl:413 [inlined]
 [4] #run#536(::Bool, ::typeof(run), ::Cmd) at .\process.jl:727
 [5] run at .\process.jl:726 [inlined]
 [6] #newsite#1(::String, ::Bool, ::Bool, ::typeof(newsite), ::String) at C:\Users\vbhanot\.julia\packages\JuDocTemplates\a90et\src\JuDocTemplates.jl:51
 [7] newsite(::String) at C:\Users\vbhanot\.julia\packages\JuDocTemplates\a90et\src\JuDocTemplates.jl:31
 [8] top-level scope at none:0

If I navigate to the `infra` subdirectory, a favicon.png file _is_ present.

I read that Thibaut had added the chmod to deal with file permissions in the first place but it seems to be not working on my machine.

NB: I have not installed any of the external dependencies: Python, Node.js or highlight.js.

**Comment by tlienart** [comment]
Hello, thanks for reporting this, would you mind reporting your version of JuDocTemplates? I suspect that may be the issue and updating might help.

To clarify, JuDoc's `newsite` function is given by the package `JuDocTemplates`  which contains the layout files etc. Some time back I had issues with this because of the way the Pkg manager puts files in read-only mode  when you `add` a package. So now `newsite` moves files around and also `chmod` them to `644` to make them editable. 

The error you quote is odd though (i.e. that it fails on a file that you can see) and unfortunately I can't reproduce it (but I'm not on Windows).

Oh and could you also report whether any other actual file gets created in your `Test` directory? if so then that means that the `chmod` call works.

(I apologise for telling you to try a number of stuff, as I don't have Windows it's harder to debug, thanks!)

**Comment by tlienart** [comment]
OK so I checked a bit more on Google it seems it's related to Windows and the  fact that the shell is not fully functional on Windows.  So it's confusing because it's saying the file cannot be found  but it's not the `favicon` file that it can't find, it's the `chmod` program. 

What I could do is modify `newsite` so that it only copies the file over without `chmod` and the user can then set the access rights of the files themselves, I'm  not sure how that stuff works  on windows.

**Comment by virenbhanot** [comment]
Hi Thibaut, thanks for the quick reply. I couldn't find a way to establish the version of JuDocTemplates since it wasn't installed using Pkg explicitly, so my trick of `Pkg.installed()` didn't work. Where else could I find the version?

Also, it creates much of the folder structure. `assets`, `libs` and `src` are all successfully created.

**Comment by tlienart** [comment]
Ok could you please try the  following:

(in some disposable folder)

```julia
julia> activate .
(v1.x) pkg> add JuDocTemplates#chmod
julia> using JuDocTemplates
julia> newsite("test")
julia> # assuming that didn't fail
(v1.x) pkg> add JuDoc
julia> using JuDoc
julia> serve()
```

and report?  the only difference is the use of `FileSystem.chmod` instead  of  trying to run  it in shell  via  backticks which seems to  cause issues on windows.

Thanks!

**Comment by virenbhanot** [comment]
I am unable to install that branch. I get the following error: 

> ERROR: Unsatisfiable requirements detected for package JuDoc [4ca9428c]:                                                 JuDoc [4ca9428c] log:                                                                                                   ├─possible versions are: [0.1.0-0.1.3, 0.2.0, 0.3.0-0.3.8] or uninstalled                                               ├─restricted to versions 0.3.8 by an explicit requirement, leaving only versions 0.3.8                                  └─restricted by compatibility requirements with JuDocTemplates [6793090a] to versions: [0.1.0-0.1.3, 0.2.0, 0.3.0-0.3.5] or uninstalled — no versions left                                                                                        └─JuDocTemplates [6793090a] log:                                                                                          ├─possible versions are: 0.3.0 or uninstalled                                                                           └─JuDocTemplates [6793090a] is fixed to version 0.3.0      

I removed `JuDoc` and reinstalled just to be sure, but the error was still repeated. I confirm I'm still on v0.3.8.

**Comment by tlienart** [comment]
Yes sorry, could you please do this in a separate environment? that should reduce the chance of getting version clashes so

```julia
julia> mkdir("disposable")
julia> cd("disposable")
julia> using Pkg; Pkg.activate(".")
julia> Pkg.add(PackageSpec(url="https://github.com/tlienart/JuDocTemplates.jl", rev="chmod"))
```

Thanks for your patience!

**Comment by virenbhanot** [comment]
HI Thibaut. It worked! I get the message below:

> ✓ Website folder generated at "test" (now the current directory).
→ Use serve() from JuDoc to see the website in your browser.

Where should I go next? Also, I tried `serve()` just for kicks but it came up as not defined. I guess this is because there _is_ no JuDoc in this environment at the moment.

**Comment by tlienart** [comment]
Fantastic! ok now I just have to  do  a patch release of JuDocTemplates with the changes and also one with the Project.toml update for JuDoc and everything will work again.

Thanks a lot for your input!

**Comment by virenbhanot** [comment]
Thanks for your help! Looking forward to using JuDoc.

**Comment by tlienart** [comment]
JuDoc 0.3.9 and JuDocTemplates 0.3.1 have been released so you can now `rm JuDocTemplates`  and `add JuDoc` and `up` and the whole lot should work 🎉

**Comment by virenbhanot** [comment]
Worked like a charm! Thanks a tonne.
