### ISSUE TITLE
html code block is evaluated instead of inserted as is

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/JuDoc.jl#325]
I guess it is a bug. If I insert the following code block ( from the [docs](https://tlienart.github.io/JuDoc.jl/dev/man/syntax/#Using-raw-HTML-1) ), it is processed as an html block and not shown as a block quote.
```
~~~
<div class="row">
  <div class="container">
    <img class="left" src="/assets/infra/rndimg.jpg">
    <p> Marine iguanas are truly splendid creatures. </p>
    <p> Evolution is cool. </p>
    <div style="clear: both"></div>      
  </div>
</div>
~~~
```

See an example [here](https://csertegt3.github.io/JuDocPlottest/pub/menu8.html), with [source](https://github.com/cserteGT3/JuDocPlottest/blob/master/src/pages/menu8.md)

**Comment by cserteGT3** [comment]
Okay, this is weird. It works on github pages, but doesn't locally (screenshot included). You can reproduce by pulling the repo and running `] instantiate` and `using JuDoc; serve()`
![image](https://user-images.githubusercontent.com/26418354/71533888-93cfe880-28fb-11ea-9afe-0ea9ffd18b80.png)

**Comment by tlienart** [comment]
Ok so I may be misunderstanding your issue, apologies if that's the case. Your code:

`````markdown
@def title = "Issue325"
@def hasplotly = true
(...)
Some text here in the "standard" layout then you can inject raw HTML:

```
~~~
<div class="row">
  <div class="container">
    <img class="left" src="/assets/infra/rndimg.jpg">
    <p> Marine iguanas are truly splendid creatures. </p>
    <p> Evolution is cool. </p>
    <div style="clear: both"></div>      
  </div>
</div>
~~~
```
(...)
`````

So from looking at this, I'm assuming that you want to  show actual HTML, i.e. that you are expecting something that looks like:

```html
<div class="row">
  <div class="container">
    <img class="left" src="/assets/infra/rndimg.jpg">
    <p> Marine iguanas are truly splendid creatures. </p>
    <p> Evolution is cool. </p>
    <div style="clear: both"></div>      
  </div>
</div>
```

If that's the case, then you need to be aware of one thing: if you just leave HTML inside a code block, it will still be rendered (this is not a JuDoc problem see [this SO post](https://stackoverflow.com/questions/11386586/how-to-show-div-tag-literally-in-code-pre-tag)), the HTML must be **escaped** see [this point in the doc](https://tlienart.github.io/JuDocWeb/pub/faq/technical.html#how_to_show_html_code) 

Further you must have `@def hascode = true` this is why you have this shitty rendering of code:

<img width="621" alt="Screen Shot 2019-12-28 at 00 12 35" src="https://user-images.githubusercontent.com/10897531/71535527-c7fcd680-2906-11ea-89dc-3cc513f80076.png">

Does that answer your question? otherwise can you be more specific about what you want to  appear on your page?

**Comment by cserteGT3** [comment]
First of all, I completely missed the new documentation  (I just bookmarked the docs and have beeing using it since), therefore I did not find the FAQ section. It looks awesome btw!
And yes, you perfectly answered my question! Thanks!
(You can ignore the `using LinearAlgebrah` nonsene, it was just for myself.)
I guess, I should just learn html before moving on...

**Comment by tlienart** [comment]
> I guess, I should just learn html before moving on...

Don't worry, I'm also fairly new to HTML and JuDoc kind of stemmed from my frustration of coding in plain HTML which I find a bit shit and difficult to maintain but clearly that also shows that I'm not very good  with it...

Anyway, keep the feedback coming please, it's very encouraging and it helps  add things to the docs that others may find  useful  some day or, to add features for things that help people. Ideally I'd like the tool to "just work" intuitively without having to  require the  users to know that much web-dev...
